services:
  traefik:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    networks:
      - jean-piarre-foucault
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jean-piarre-foucault:
    external: true
    name: jean-piarre-foucault-dir_default
