name: Setup & install project

runs:
  using: "composite"
  steps:
    - name: DDEV config + start
      run: |
        ddev config global --instrumentation-opt-in=false
        ddev start
      shell: bash

    - name: Install dependencies
      run: |
        ddev composer install --no-dev --no-progress --prefer-dist --optimize-autoloader
      shell: bash

    - name: Install site
      run: |
        sed -i '/if (file_exists(\$app_root/,/}/ s/^# *//' "web/sites/default/settings.php"
        cp .ddev/files/settings.local.php web/sites/default/settings.local.php
        ddev drush site:install 'minimal' --existing-config --account-name=admin --account-pass=admin -y
        ddev update
      shell: bash
