name: Setup & install project

runs:
  using: "composite"
  steps:
    - name: Setup project
      run: |
        cp ".env.example" ".env"
        sed -i 's/^DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sudo rm -Rf web/sites
        composer install --no-progress --prefer-dist --optimize-autoloader
        mkdir -p "web/sites/default"
        cp ".docker/files/settings.php.default" "web/sites/default/settings.php"
      shell: bash

    - name: Test project install
      run: |
        vendor/bin/drush site-install 'minimal' --config-dir=../config/sync --account-name='admin' --account-pass='admin' --yes
        vendor/bin/drush deploy
        vendor/bin/drush locale-check
        vendor/bin/drush locale-update
        vendor/bin/drush cr
      shell: bash
