#!/bin/bash

## Description: Initialize the project
## Usage: init
## Example: "ddev init"

rm -Rf "$DDEV_APPROOT/vendor" "$DDEV_APPROOT/web/modules/contrib" "$DDEV_APPROOT/web/themes/contrib" "$DDEV_APPROOT/web/core" "$DDEV_APPROOT/web/sites"
cp "$DDEV_APPROOT/python/jean-pyarre/templates/v5.html.example" "$DDEV_APPROOT/python/jean-pyarre/templates/v5.html"
cp "$DDEV_APPROOT/python/jean-pyarre/versions/v5.py.example" "$DDEV_APPROOT/python/jean-pyarre/versions/v5.py"
ddev composer install --prefer-dist --optimize-autoloader
# shellcheck disable=SC2016
sed -i '/if (file_exists(\$app_root/,/}/ s/^# *//' "$DDEV_APPROOT/web/sites/default/settings.php"
cp "$DDEV_APPROOT/.ddev/files/settings.local.php" "$DDEV_APPROOT/web/sites/default/settings.local.php"
ddev perm
ddev drush site:install 'minimal' --existing-config --account-name=admin --account-pass=admin -y
ddev update
ddev drush fill-lotto-draws-data --all
ddev drush cron
ddev drush cr
ddev launch
