#!/bin/bash

## Description: Init or re-init project
## Usage: init
## Example: "ddev init"

WEB_PATH="$DDEV_APPROOT/web"
EXCLUDES_PATH=(
  "$WEB_PATH/sites/default"
  "$WEB_PATH/sites/default/settings.local.php"
  "$WEB_PATH/sites/default/settings.php"
  "$WEB_PATH/sites/default/services.yml"
  "$WEB_PATH/sites/development.services.yml"
)
EXCLUDE_EXPR=""

# Exclude expression args for find command.
for e in "${EXCLUDES_PATH[@]}"; do
  if [ -z "$EXCLUDE_EXPR" ]; then
    EXCLUDE_EXPR="-path \"$e\""
  else
    EXCLUDE_EXPR="$EXCLUDE_EXPR -o -path \"$e\""
  fi
done

# Stop project if running.
ddev stop
# Remove unversioned files if exists.
rm -Rf "$DDEV_APPROOT/vendor" "$DDEV_APPROOT/web/modules/contrib" "$DDEV_APPROOT/web/themes/contrib" "$DDEV_APPROOT/web/core"
eval "find \"$WEB_PATH/sites\" -mindepth 1 ! \( $EXCLUDE_EXPR \) -exec rm -rf {} +"
# Copy Python example files.
cp "$DDEV_APPROOT/python/jean-pyarre/templates/v5.html.example" "$DDEV_APPROOT/python/jean-pyarre/templates/v5.html"
cp "$DDEV_APPROOT/python/jean-pyarre/versions/v5.py.example" "$DDEV_APPROOT/python/jean-pyarre/versions/v5.py"
# Install dependencies.
ddev composer install
# Usage of settings.ddev.php.
chmod -R 777 "$DDEV_APPROOT/web/sites/default"
cp "$DDEV_APPROOT/.ddev/files/settings.ddev.php" "$DDEV_APPROOT/web/sites/default/settings.ddev.php"
# Install site.
ddev drush site:install 'minimal' --existing-config --account-name=admin --account-pass=admin -y
# Set permissions.
ddev perm
# Update site.
ddev update
# Init data.
ddev drush fill-lotto-draws-data --all
ddev drush cron
# Clear caches.
ddev drush cr
# Launch project.
ddev launch
