#!/bin/bash

## Description: Apply recommended Drupal permissions
## Usage: perm
## Example: "ddev perm"

find web -type d -exec chmod 755 '{}' \; || true
find web -type f -exec chmod 644 '{}' \; || true
find web/sites -type d -name files -exec chmod 775 '{}' \; || true
find web/sites/*/files -type d -exec chmod 775 '{}' \; || true
find web/sites/*/files -type f -exec chmod 664 '{}' \; || true
find web/sites/*/settings* -type f -exec chmod 444 '{}' \; || true
