ARG PYTHON_TAG=3.13
ARG PYTHON_PORT=5000
FROM --platform=$BUILDPLATFORM python:${PYTHON_TAG} AS builder

WORKDIR /code

COPY .docker/python/requirements .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements

COPY python/jean-pyarre .
COPY .env .

ENV FLASK_APP=jean-pyarre.py \
    FLASK_ENV=development \
    FLASK_RUN_HOST=0.0.0.0

EXPOSE ${PYTHON_PORT}

CMD ["flask", "run"]

FROM builder AS dev-envs

RUN <<EOF
apk update
apk add git
EOF

RUN <<EOF
addgroup -S docker
adduser -S --shell /bin/bash --ingroup docker vscode
EOF

COPY --from=gloursdocker/docker / /

CMD ["flask", "run"]
