#!/usr/bin/env bash

## Init/reinit project.
##
## Usage: fin init

# Abort if anything fails
set -e

if [ -x "$(command -v fin)" ]; then
  # Reset project.
  fin project reset

  # Install vendor.
  fin composer install --no-progress --prefer-dist --optimize-autoloader

  # Copy settings.php.
  chmod -R 755 "${PROJECT_ROOT}/${DOCROOT}/sites/default"
  cp "${PROJECT_ROOT}/.docksal/files/settings.php.default" "${PROJECT_ROOT}/${DOCROOT}/sites/default/settings.php"
  chmod 644 "${PROJECT_ROOT}/${DOCROOT}/sites/default/settings.php"

  # Install site.
  fin drush site-install 'minimal' --config-dir=../config/sync --account-name='admin' --account-pass='admin' --yes
  fin drush deploy
  fin drush cache-rebuild

  # Fill data.
  fin drush fill-lotto-draws-data --all

  # Fill stats.
  fin drush fill-lotto-stats
fi
