#!/usr/bin/env bash

## Description: Update stack after a core or a module update
## Usage: post-update
## Example: ddev post-update

composer patches-relock
composer install --no-progress
composer update --lock
composer normalize
drush updatedb --no-cache-clear
drush cr
drush cex -y
