#!/usr/bin/env bash

## Description: Run GrumPHP to check quality
## Usage: quality {tasks}
## Example: ddev quality (run GrumPHP with all tasks)
## Example: ddev quality phpcs,phpstan (run GrumPHP only with PHPCS and PhpStan tasks)

php ./vendor/bin/grumphp run --testsuite=quality --tasks="$1"
