#!/usr/bin/env bash

## Description: Run GrumPHP to check quality on Git diff
## Usage: quality-check
## Example: ddev quality-check

cd "$DDEV_APPROOT" || exit

it -c diff.mnemonicprefix=false -c diff.noprefix=false diff --raw -r -p -m -M --full-index --no-color | php ./vendor/bin/grumphp git:pre-commit
