#!/usr/bin/env bash

## Description: Update project
## Usage: update
## Example: ddev update

composer install --no-progress
sudo cp "$DDEV_APPROOT/.ddev/files/settings.ddev.php" "$DDEV_APPROOT/web/sites/default/settings.ddev.php"
drush deploy
drush locale-check
drush locale-update
drush cr
