[php]
date.timezone = 'Europe/Paris'
memory_limit = 1024M
max_input_vars = 1000
zend.assertions=1
error_reporting= E_ALL
display_errors=On
pcov.directory=/var/www/html/web
pcov.exclude="~\/(core|libraries|modules\/contrib|themes\/contrib|sites|tests)\/~"
