name: jean-piarre-foucault
type: drupal11
docroot: web
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "11.4"
use_dns_when_possible: true
timezone: Europe/Paris
composer_version: 2.8.9
web_environment:
    - DRUSH_ALLOW_XDEBUG=1
corepack_enable: false
ddev_version_constraint: '>= 1.24.6'
messages:
  ticker_interval: -1
