services:
  python:
    container_name: ddev-${DDEV_SITENAME}-python
    image: python:3.14-alpine
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    build:
      context: ..
      dockerfile: ./.ddev/python/Containerfile
      target: builder
      args:
        PYTHON_TAG: 3.14-alpine
        PYTHON_PORT: 5000
    volumes:
      - ".:/mnt/ddev_config"
    environment:
      FLASK_RUN_PORT: 5000
      FLASK_APP: jean-pyarre
      FLASK_RUN_HOST: 0.0.0.0
    depends_on:
      - db
