services:
  python:
    restart: always
    image: python:3.13-alpine
    build:
      context: ..
      dockerfile: ./.ddev/python/Containerfile
      target: builder
      args:
        PYTHON_TAG: 3.13-alpine
        PYTHON_PORT: 5000
    container_name: ddev-${DDEV_SITENAME}-python
    environment:
      FLASK_RUN_PORT: 5000
