name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  composer:
    strategy:
      matrix:
        include:
          - operating-system: 'ubuntu-latest'
            php-version: '8.4'
            job-description: 'on Linux'

          - operating-system: 'windows-latest'
            php-version: '8.4'
            job-description: 'on Windows'

          - operating-system: 'macos-latest'
            php-version: '8.4'
            job-description: 'on macOS'

    name: Composer with ${{ matrix.php-version }} ${{ matrix.job-description }}

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup composer
        uses: ./.github/actions/composer
  php:
    name: Run quality tools (GrumPHP)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup composer
        uses: ./.github/actions/composer

      - name: Run GrumPHP
        run: php ./vendor/bin/grumphp run
  python:
    name: Run python + security scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r .ddev/python/requirements

      - name: Check Python app
        run: python python/jean-pyarre/jean-pyarre.py --check

      - name: PyCharm Python Security Scanner
        uses: johnatas-x/pycharm-security@master
        with:
          path: python/
