name: Update data for current version

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: wodby/mariadb:11.4-3.30.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: ./.github/actions/php

      - name: Setup & install project
        uses: ./.github/actions/project

      - name: Test data fill
        run: |
          vendor/bin/drush fill-lotto-draws-data --all
          vendor/bin/drush cr

      - name: Get ZIP file URL from PHP
        id: get_zip_url
        run: |
          URL=$(vendor/bin/drush php:eval "echo \Drupal\jpf_import\Api\Sto::buildDownloadUrl(\Drupal\jpf_store\Enum\Versions::currentVersion());")
          echo "ZIP_URL=$URL" >> $GITHUB_ENV

      - name: Download ZIP & extract CSV file
        run: |
          wget -O /tmp/loto_201911.zip "$ZIP_URL"
          unzip -o /tmp/loto_201911.zip -d /tmp/

      - name: Count lines in old and new CSV
        id: check_lines
        run: |
          OLD_FILE="web/modules/custom/jpf_store/assets/doc/v5/loto_201911.csv"
          NEW_FILE="/tmp/loto_201911.csv"
          OLD_LINES=$(wc -l < "$OLD_FILE" || echo 0)
          NEW_LINES=$(wc -l < "$NEW_FILE" || echo 0)

          if [ "$NEW_LINES" -gt "$OLD_LINES" ]; then
            mv "$NEW_FILE" "$OLD_FILE"
            echo "update_needed=true" >> $GITHUB_ENV
          else
            echo "update_needed=false" >> $GITHUB_ENV
          fi

      - name: Push diff
        if: env.update_needed == 'true'
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'web/modules/custom/jpf_store/assets/doc/*'
          author_name: update-data[bot]
          author_email: 203315439+jpf-update-data@users.noreply.github.com
          commit: --signoff -n
          message: 'Update data'
          push: 'https://x-access-token:${{ secrets.UPDATE_BOT_TOKEN }}@github.com/johnatas-x/Jean-Piarre-Foucault.git main --set-upstream'
